[features]
default = ["ogl"]
ogl = []

[package]
name = "glwindow"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[dependencies]
shader_ast = {path="./shader_ast"}
glutin = "*"
gl = "*" 
rand = "*"
scoped_threadpool = "*"